spring:
  application:
    name: Art
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/art
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8008
private:
  session-timeout: 10